notifications:
  slack:
    secure: u+vSv7yZ4NCiBfdBczCV0j5vJARgOoX0EwA7xs8zN7tog5lBgyTB5R8AJbc5LV9jKXzarJLZibXePiBQysZi4zCnkVJGxzoOUO4dV/FDAZRa1v7MyPlIh71yDYK1a5uZPUd6OQWdwC2XlKIj1kUn39YdG60vheGNj6DhHRbPJtya6sk1vrPFqbLIh0qqTPGKifmugDJ5c8hMiT3c9tYQoA03Setl11EdWQGgTbc+dz3k79kbcQQ41xslcRuuHYMXnqFDDopwfqa/Oq4aJy+cFRjOpd8vhtSvKkg0pn4Xek4Hu5iixKIDgV7VWRPF848ePF6Mz8V1Iz/iz61Ro8te2p6jPlKmtE+qWe9YEUtweBTBwvjtQIORINn7YMLUhEqgUhiaLgCPvSCJbrLgEkRLzFxQZ1KpwCBrwaD1UuSTo0zmqblRoIumtm81Jd7LraKl0pA6dIHkAQla8f+NxvfhGeej95tTDvdzTEwZWaFdVsOa4j8CEzvqXr1CGh+Q+vGZYhhEUd9zkMQFfuIRNqk7WyEK1dzXvf+KwH+s1ncl4pXYgdk6Jgf+ItGH6zc1aoU1v+Wg4Ek6KaBxJ2hsNasS3Td2BQahu6a7K0w1ffnRac6HTXlgNEsOyJEt3h/Vz0QV1voyeish7VR2/H1hLGxCfNVo6i7mLesU0MmrFPejYCk=
  email:
    on_success: never
    on_failure: always
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- if ! command -v conda > /dev/null; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda -u; conda config --add
  channels conda-forge; conda config --set always_yes yes; conda update --all; conda
  install tectonic==0.1.11; fi
- conda config --add channels conda-forge
- conda config --set always_yes yes
- conda install tectonic==0.1.11
- conda info -a
cache:
  directories:
  - "$HOME/miniconda"
script:
- cd ./src/
- tectonic ./random-math.tex --print
- cd ../
- cd ./style-guides/src/
- tectonic ./latex-style-guide.tex --print
- cd ../../
- cd ./file-templates/
- tectonic ./homework.tex --print
- tectonic ./presentation-thomas.tex --print
- cd ../
# Tests
- cd ./personal-packages/thomas/
- tectonic ./package-test-article.tex --print
- tectonic ./package-test-exam.tex --print
- cd ../../
# MWEs
- cd ./mwe/
- tectonic ./biber-mwe.tex --print
- tectonic ./bibtex-mwe.tex --print
- tectonic ./index-mwe.tex --print
- cd ../
deploy:
  provider: releases
  api_key:
    secure: jOsB6YZ29f2ATmLgJs4+9+sBYAIGMCCamaZBaUytOW5XBN5MbaPkryuKZhcuwUd/Xn6bDliKkafF3Qw4awq/djwbPUBsVKhi6zbSLEIoNIkUzyxWB7mpu02xACIOQoFjSsiPyAyrvFnpVTTqoAjeE3pC8QObiDyDH/dqI+PlcC4syMUDq4C2u1x9d22vfe6uHP3hJvcusVtc6VrcuC0bEaRtFq5OV2qJkdaIRrccZj+DwP1IoL1l02qxcCvSqg6luY1dLykC5x7c147R2ldt71CldDbh4V0T3bE1ho7rOfpFHDTcYvdEhGdABbr+BWTl7Cc8kyn/vvyWWqbAEnwIvcZHeMe1BZGzENjEsmRuUpP9twaVWkR+6ZZgUtqhH5pWZ8fJtAlCd+xL0XVurbSpgC4LC0Jwf4drScqgW0JVmVb8Ck+KTZ897kaneFghxrPJeK/krtzncP9MHEpmk17z2Pos23tudpkt/yleUgi3O4mv5lS3qP+U0uFEcGQBPwGKwLMb5rYZ3mPWp21dx01css86sABfhnhdTswENVpYoK/orJvYU8whPuwtrm6T5J0sQ9LQ1BJ3mvPJLnBNZ7RwTflppG3xolEKLvakSf/qA1AEBfpZV33qGLE1VLY4N+G+vx0PYHbtpHCLcQsZOZ1YINWc+IvVFTuWja7G9PNTTvU=
  file:
  - "./src/random-math.pdf"
  - "./style-guides/src/latex-style-guide.pdf"
  skip_cleanup: true
  on:
    tags: true
    branch: master
